// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AuctionType,
} from "./types";


export default __t.row({
  id: __t.u32().primaryKey(),
  enabled: __t.bool(),
  matchSizeMin: __t.u32().name("match_size_min"),
  matchSizeMax: __t.u32().name("match_size_max"),
  intervalMs: __t.u64().name("interval_ms"),
  get auctionType() {
    return AuctionType.name("auction_type");
  },
});
