// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  AuctionType,
} from "./types";

export default {
  enabled: __t.bool(),
  matchSizeMin: __t.u32(),
  matchSizeMax: __t.u32(),
  intervalMs: __t.u64(),
  get auctionType() {
    return AuctionType;
  },
};
