// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimCredentialReducer from "../claim_credential_reducer";
import ConnectIdReducer from "../connect_id_reducer";
import CreateTeamReducer from "../create_team_reducer";
import JoinTeamReducer from "../join_team_reducer";
import LeaveTeamReducer from "../leave_team_reducer";
import MintCredentialNonceReducer from "../mint_credential_nonce_reducer";
import PromoteToOwnerReducer from "../promote_to_owner_reducer";
import SetMatchmakerEnabledReducer from "../set_matchmaker_enabled_reducer";
import SpawnSimulatedBotReducer from "../spawn_simulated_bot_reducer";
import StartMatchReducer from "../start_match_reducer";
import StartMatchForReducer from "../start_match_for_reducer";
import StartTournamentReducer from "../start_tournament_reducer";
import SubmitBidReducer from "../submit_bid_reducer";
import SubmitWordReducer from "../submit_word_reducer";

export type ClaimCredentialParams = __Infer<typeof ClaimCredentialReducer>;
export type ConnectIdParams = __Infer<typeof ConnectIdReducer>;
export type CreateTeamParams = __Infer<typeof CreateTeamReducer>;
export type JoinTeamParams = __Infer<typeof JoinTeamReducer>;
export type LeaveTeamParams = __Infer<typeof LeaveTeamReducer>;
export type MintCredentialNonceParams = __Infer<typeof MintCredentialNonceReducer>;
export type PromoteToOwnerParams = __Infer<typeof PromoteToOwnerReducer>;
export type SetMatchmakerEnabledParams = __Infer<typeof SetMatchmakerEnabledReducer>;
export type SpawnSimulatedBotParams = __Infer<typeof SpawnSimulatedBotReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type StartMatchForParams = __Infer<typeof StartMatchForReducer>;
export type StartTournamentParams = __Infer<typeof StartTournamentReducer>;
export type SubmitBidParams = __Infer<typeof SubmitBidReducer>;
export type SubmitWordParams = __Infer<typeof SubmitWordReducer>;

